### ISSUE TITLE
Upload links with deletion url also gets copied

### ISSUE THREAD

**Issue by WhoTook7050** [SrS2225a/custom_uploader#2]
On sharex it is able to differentiate between the file url and the deletion link url, but here is copies both the file url and deletion url

Example result:
https://toso.akatsuki-4.life/yYCZV3WrMjhttps://api.horizon.pics/delete/96a188a8-cf55-4e35-8f72-1bb26c4b8c87

Expected result:

https://toso.akatsuki-4.life/yYCZV3WrMj

Add file data to request body arguments is off because I would get an error "Unprocessable Entity"

**Comment by WhoTook7050** [comment]
{"RequestURL":"https://api.horizon.pics/upload",
"FileFormName":"file",
"Headers":{"Authorization":"Bearer [secret key]"},
"Arguments":{},
"URL":"$json:data.fileLink$"}

Exported to sxcu, edited for formatting

It's probably from $json:data.fileLink$, but sharex is able to differentiate between the two links just fine.

**Comment by WhoTook7050** [comment]
This error does NOT occur with certain certain sxcu configs.

Example of one that works out-of-the-box:

{
      "Version": "13.4.0",
      "Name": "read-my-man.ga",
      "DestinationType": "None",
      "RequestMethod": "POST",
      "RequestURL": "https://read-my-man.ga/upload",
      "Parameters": {
        "randomKey": "true"
      },
      "Body": "MultipartFormData",
      "FileFormName": "file",
      "URL": null,
      "ThumbnailURL": null,
      "DeletionURL": null,
      "ErrorMessage": null
    }

**Comment by SrS2225a** [comment]
Hi, that is indeed a problem that it adds the deletion url with the link. Is api.horizion.pics the current sharex configuration file you are using for custom uploader? If not, could you send me that to take a further look with? Also, are you using the response url field?

**Comment by WhoTook7050** [comment]
api.horizon.pics is the current sharex config file, unchanged from the .sxcu

In response url it would be the "$json:data.fileLink$" (no quotes). I should note that on sharex, it is able to copy only the file url, but it does list the deletion url (if i recall correctly, I cannot recheck because I am away from my computer)

**Comment by SrS2225a** [comment]
Hi, I have fixed your issue. Turns out it was just a small little oversight with the with the way my url response parser was handing urls. You will need to get it as a release though since I am still working with f-droid and google play to get it published on their repositories. But you, should not have any more issues. Enjoy :)

**Comment by WhoTook7050** [comment]
Can confirm it works fine now!
Thank you for developing the app!
