### ISSUE TITLE
Support IP addresses in URL's

### ISSUE THREAD

**Issue by mhio** [SrS2225a/custom_uploader#6]
### Describe The Bug

Setting up a host with http://192.168.1.100/ results in an "Please enter a valid url" validation message. 

The [regex](https://github.com/SrS2225a/custom_uploader/blob/753d6f6d1c745e4c06af3d3e5ca00e581b9e1bfb/lib/views/add_new.dart#L319C36-L319C115) is a bit restrictive, even for [tlds](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains)

Some samples: https://regexr.com/7ooub

### To Reproduce

Open "Add" form.

Enter URLS like:
- whatever.accountant
- x.com/test
- http://10.10.10.10/test
- https://192.168.1.1:5000/test
- https://[fe80::20c:29ff:fee2:1de]:5000/test
- https://[fe80::20c:29ff:fee2:1de]/test

### Expected Behavior

Valid URLs validate

### App Version

1.1.0

**Comment by SrS2225a** [comment]
Thanks for your report. It did not cross my mind at the time to support regular ip addresses than just domains, and the http:// restriction is because of the http library I use. I will take a look at it and should be fixed in the next app version with your improvements which is coming soon.

**Comment by SrS2225a** [comment]
Thanks for bearing with me, the bug you reported has been fixed, and Custom Uploader will now support ip's. You should see the new version on F-Droid soon
