### ISSUE TITLE
Include Uploaders

### ISSUE THREAD

**Issue by Nzzyme** [SrS2225a/custom_uploader#9]
### What you want to be added

Can you include some uploaders in your app so that the user does not have to add them to use them.

### Why you want this feature

As common users do not know how to add the uploaders, it would be good to include some uploaders in the app. The instructions are too technical for a common user to follow.

**Comment by Rihcus** [comment]
Here are some configs for catbox.moe and litterbox.catbox.moe 

Use with account hash:
[catbox_with_account.json](https://github.com/SrS2225a/custom_uploader/files/13891670/catbox_with_account.json)

Use without account:
[catbox.json](https://github.com/SrS2225a/custom_uploader/files/13891671/catbox.json)

Files expire after 72hr:
[litterbox.json](https://github.com/SrS2225a/custom_uploader/files/13891672/litterbox.json)

**Comment by SrS2225a** [comment]
Thank you for your feedback. Agreed, I had this feature planned recently for a while now for a future release along with a adding simple view of the add uploader page to make it easier for new users to add their favorite file hosts, so it should be coming soon. Until then, I will keep this issue open

**Comment by SrS2225a** [comment]
Hello, I just wanted to let your know that I have added your feature request and the new version with it should be out by tomorrow or tomorrow after.  If anyone wants to contribute their own presets, you can just simply edit the yaml file in `lib/assets/preset_uploaders.yaml`, which would be greatly appreciated.

**Comment by SrS2225a** [comment]
Release out now!

**Comment by clach04** [comment]
Clickable link for lazy people like me on mobile https://github.com/SrS2225a/custom_uploader/blob/master/lib/assets/preset_uploaders.yaml
